const
    BOARD_LENGTH=8,
    BOARD_ID="board",
    BOARD_CLASS=BOARD_ID,
    BOARD_ROW_CLASS=BOARD_CLASS+"_row",
    BOARD_ROW_CELL_CLASS=BOARD_ROW_CLASS+"_cell",
    WHITE="white",
    BLACK="black"
;